#!/bin/bash

#
# Copyright SAS Institute
#
#  Licensed under the Apache License, Version 2.0 (the License);
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#


#set -ex
jupyter kernelspec list
jupyter nbextension list


jupyter nbextension install --py sas_kernel.showSASLog --user
jupyter nbextension enable sas_kernel.showSASLog --py

jupyter nbextension install --py sas_kernel.theme --user
jupyter nbextension enable sas_kernel.theme --py

jupyter nbextension list

cd /tmp || exit
git clone https://github.com/jld23/sas_kernel_ext.git

cd /tmp/sas_kernel_ext/sas_log_viewer_v2 || exit
pip install .

cd /tmp/sas_kernel_ext/jlab_create_sas_file || exit
pip install .

cd /tmp/sas_kernel_ext/sas2nb || exit
pip install .

jupyter server extension enable --py --sys-prefix sas2nb

#jlpm
#jlpm build

#jupyter lab build
#jupyter lab build --dev-build=False
